render:
  width: 300
  height: 203
stages:
  - fragmentShaderPath: "../demo/divergence/divergence.frag"
    textures:
      - path: "C:/msys64/home/smith/git/github.com/smithjacobj/glslfilter/demo/crt-singlestage/input.png"
        name: "inputTexture"
    uniforms:
      - name: "count"
        type: "int"
        value: 3
      - name: "colorFilters"
        type: "[]FloatVec3"
        value:
          - [0.98, 0.87, 0.07] # yellow
          - [0, 0.62, 0.86] # blue
          - [0.76, 0.25, 0.59] # pink
      - name: "colorDivergencePx"
        type: "[]IntVec2"
        value: 
          - [-32,0] # yellow
          - [0,0] # blue
          - [32,0] # pink