render:
  width: ${width}
  height: ${height}
stages:
  - fragmentShaderPath: "${script_path}/divergence.frag"
    textures:
      - path: "${source_path}"
        name: "inputTexture"
    uniforms:
      - name: "count"
        type: "int"
        value: 3
      - name: "colorFilters"
        type: "buffer"
        value:
          - [0.98, 0.87, 0.07] # yellow
          - [0, 0.62, 0.86] # blue
          - [0.76, 0.25, 0.59] # pink
      - name: "colorDivergencePx"
        type: "buffer"
        value: 
          - [-32,0] # yellow
          - [0,0] # blue
          - [32,0] # pink