render:
  width: ${width}
  height: ${height}
stages:
  - fragmentShaderPath: "${script_path}/divergence.frag"
    textures:
      - path: "${source_path}"
        name: "inputTexture"
    uniforms:
      - name: "colorFilters"
        value:
          yellow: [0.98, 0.87, 0.07]
          blue: [0, 0.62, 0.86]
          pink: [0.76, 0.25, 0.59]
      - name: "colorDivergencePx"
        value: 
          yellow: [-32,0]
          blue: [0,0]
          pink: [32,0]