render:
  width: 2940
  height: 1956
stages:
  - fragmentShaderPath: "../demo/crt/demo_stage1.frag"
    textures:
      - path: "../demo/crt-singlestage/input.png"
        name: "baseTexture"
      - path: "../demo/crt-singlestage/phosphor.png"
        name: "tileTexture"
  - fragmentShaderPath: "../demo/crt/demo_stage2.frag"
  - fragmentShaderPath: "../demo/crt/demo_stage3.frag"
  - fragmentShaderPath: "../demo/crt/demo_stage4.frag"
